FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

ENV \
  PACKAGES="\
    git \
    cmake \
    vim \
    make \
    wget \
    gnupg \
    build-essential \
    software-properties-common \
    gdb \
    zip \
    " \
  VNC_PACKAGES="\
    xfce4 \
    xfce4-goodies \
    tightvncserver \
  " \
  PYTHON_PACKAGES="\
    libreadline-gplv2-dev \
    libncursesw5-dev \
    libssl-dev \
    libsqlite3-dev \
    tk-dev \
    libgdbm-dev \
    libc6-dev \
    libbz2-dev \
    python3-pip \
    libffi-dev \
  " \
  python_version="3.7.2" \
  VNC_PASSWORD="123456"

RUN \
  apt update -y \
  && DEBIAN_FRONTEND=noninteractive apt install -y $PACKAGES $VNC_PACKAGES